### ISSUE TITLE
Multiple Values on Custom Text Field

### ISSUE THREAD

**Issue by MGUser26** [bullhorn/dataloader-app#7]
Hi,

I am currently doing an Import of candidate data into bullhorn and the ";" delimiter worked for importing multiple values to a business sector but didn't work for a custom text field. It simply added one tag which displayed as "x;y;z" for example.

As mentioned the business sector import broke them down into multiple tags but not for custom text import.

Any ideas on how to get this to work?

**Comment by ndickerson** [comment]
That's because the delimiter only works for To-Many fields, such as skills on a Candidate. If you are doing a custom text field, that is only plain text in the database. If you have field maps setup to use the custom field as a multi-value select, then you'll need to use commas to separate the values. Also note that these will be the internally stored values, not the displayed values, if the list in field maps has a separate display list.

**Comment by MGUser26** [comment]
Hi,

I thought this, problem we have is that when I quote the options as the data loader suggests (ie. "a,b,c") it displays as multiple options but the quotes are appearing within the values on Bullhorn eg. "a    b   c" (as three separate values).

Any help with this would be much appreciated.
